import path from "node:path";

const cacheManagedAssetExtensions = new Set([
  ".avif",
  ".bmp",
  ".cjs",
  ".css",
  ".eot",
  ".gif",
  ".ico",
  ".jpeg",
  ".jpg",
  ".js",
  ".mjs",
  ".otf",
  ".png",
  ".svg",
  ".ttf",
  ".webp",
  ".woff",
  ".woff2",
]);

const hexadecimalHashPattern = /^[a-f0-9]{8,64}$/i;
const mixedHashPattern =
  /^(?=.{8,64}$)(?=.*[a-z])(?=.*[A-Z0-9])[A-Za-z0-9]+$/;

export function isCacheManagedAsset(key) {
  return cacheManagedAssetExtensions.has(path.extname(key).toLowerCase());
}

export function hasContentHash(key) {
  const extension = path.extname(key);
  const stem = path.basename(key, extension);
  const tokens = stem.split(/[._-]/).filter(Boolean);
  const candidate = tokens.at(-1) ?? "";

  if (hexadecimalHashPattern.test(candidate)) {
    return true;
  }

  // Non-hex hashes generated by tools such as Vite are normally a final,
  // delimiter-separated, mixed-case/alphanumeric token.
  return tokens.length > 1 && mixedHashPattern.test(candidate);
}

export function cacheControlFor(key) {
  const extension = path.extname(key).toLowerCase();

  if (extension === ".html") {
    return "no-cache, must-revalidate";
  }

  if (isCacheManagedAsset(key) && hasContentHash(key)) {
    return "public,max-age=31536000,immutable";
  }

  return "public,max-age=3600";
}
